java_test(
    name = "HelloControllerTest",
    srcs = ["HelloControllerTest.java"],
    deps = [
        "//api/src/main/java/com/example/myproject:lib",
        "@maven//:org_hamcrest_hamcrest_library",
        "@maven//:org_springframework_boot_spring_boot_test",
        "@maven//:org_springframework_boot_spring_boot_test_autoconfigure",
        "@maven//:org_springframework_spring_beans",
        "@maven//:org_springframework_spring_test",
        "@maven//:org_springframework_spring_web",
    ],
)

java_test(
    name = "HelloControllerIT",
    srcs = ["HelloControllerIT.java"],
    deps = [
        "//api/src/main/java/com/example/myproject:lib",
        "@maven//:org_hamcrest_hamcrest_library",
        "@maven//:org_springframework_boot_spring_boot",
        "@maven//:org_springframework_boot_spring_boot_test",
        "@maven//:org_springframework_spring_beans",
        "@maven//:org_springframework_spring_test",
        "@maven//:org_springframework_spring_web",
    ],
)
